function Hd = cheby1_hpf
%CHEBY1_HPF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 11-Nov-2021 23:12:20

% Chebyshev Type I Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 100;  % Sampling Frequency

Fstop = 0.6;         % Stopband Frequency
Fpass = 1;           % Passband Frequency
Astop = 80;        % Stopband Attenuation (dB)
Apass = 0.01;        % Passband Ripple (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]
