function Hd = cheby2_hpf
%CHEBY2_HPF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 12-Nov-2021 12:37:08

% Chebyshev Type II Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 50;  % Sampling Frequency

Fstop = 0.6;         % Stopband Frequency
Fpass = 1;           % Passband Frequency
Astop = 60;          % Stopband Attenuation (dB)
Apass = 3;           % Passband Ripple (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
